name: 'BrowserStack Test'
on: [push, pull_request]
jobs:
    windows-job:
    
      name: 'BrowserStack Test on Windows'
      runs-on: windows-latest
      steps:

        - name: 'BrowserStack Env Setup'
          uses: browserstack/github-actions/setup-env@master
          with:
            username:  ${{ secrets.BROWSERSTACK_USERNAME }}
            access-key: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
            
        - name: 'BrowserStack Local Tunnel Setup'
          uses: browserstack/github-actions/setup-local@master
          with:
            local-testing: start
            local-identifier: random
            
        - name: Install dependencies
          run: dotnet restore
      
        - name: Build
          run: dotnet build --configuration Release --no-restore
 
        - name: 'Running test on BrowserStack'
          run: dotnet test --no-restore --verbosity normal
          
        - name: 'Stop BrowserStackLocal'
          uses: browserstack/github-actions/setup-local@master
          with:
            local-testing: stop
