name: 'BrowserStack Test'
on: [push, pull_request]
jobs:
	ubuntu-job:
   	name: 'BrowserStack Test on Ubuntu'
  	runs-on: ubuntu-latest
   	steps:
		
			- name: 'BrowserStack Env Setup'
				uses: browserstack/github-actions@v1.0.1/setup-env@trunk
				with:
  				username:  ${{ secrets.BROWSERSTACK_USERNAME }}
  				access-key: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
		
			- name: 'BrowserStack Local Tunnel Setup'
  			uses: browserstack/github-actions@v1.0.1/setup-local@trunk
  			with:
					local-testing: start
    			local-identifier: random
					
			- name: 'Running test on BrowserStack'
        run: dotnet test
				
			- name: 'Stop BrowserStackLocal'
  			uses: browserstack/github-actions@v1.0.1/setup-local@trunk
        with:
          local-testing: stop

